const express=require('express');
const session=require('express-session');
const pgSession=require('connect-pg-simple')(session);
const passport=require('passport');
const GoogleStrategy=require('passport-google-oauth20').Strategy;
const bcrypt=require('bcryptjs');
const helmet=require('helmet');
const crypto=require('crypto');
const {Pool}=require('pg');

const app=express();
const PORT=Number(process.env.PORT||3000);
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const FREE_CREDIT=Number(process.env.FREE_CREDIT_TOMAN||50000);
const USD_TO_TOMAN=Number(process.env.USD_TO_TOMAN||100000);
const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'').toLowerCase();
const APP_URL=process.env.APP_URL||'https://ai.bavaan.ir';
const SEGMENTS={
 developer:{workspace:'api',title:'می‌خوام API رو به اپ یا سایتم وصل کنم',desc:'کلید API، مدل‌ها، لاگ مصرف و مستندات فنی.'},
 agency:{workspace:'automation',title:'برای مشتری‌هام ربات و اتوماسیون می‌سازم',desc:'پروژه‌ها، کلیدهای جدا، n8n، تلگرام و مصرف هر مشتری.'},
 startup:{workspace:'production',title:'یک محصول AI دارم و مصرف production برام مهمه',desc:'پایداری، بودجه، route جایگزین و تحلیل هزینه.'},
 business:{workspace:'business',title:'برای کسب‌وکارم محتوا و کارهای تکراری می‌خوام',desc:'تولید محتوا، تحلیل فایل و کارهای حجمی بدون درگیری با مدل.'},
 creator:{workspace:'creative',title:'بیشتر با تصویر، ویدئو و محتوای خلاق کار می‌کنم',desc:'فضای خلاق با تمرکز روی هزینه هر خروجی.'},
 everyday:{workspace:'simple',title:'فقط می‌خوام AI کارم رو انجام بده؛ اسم مدل مهم نیست',desc:'به جای انتخاب مدل، فقط کاری که می‌خوای انجام بدی رو انتخاب کن.'}
};
const WORKSPACES={api:'API و توسعه',automation:'اتوماسیون و مشتری',production:'Production',business:'کسب‌وکار',creative:'استودیو خلاق',simple:'ساده'};

app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.urlencoded({extended:true,limit:'1mb'}));
app.use(express.json({limit:'2mb'}));
app.use('/static',express.static('public',{maxAge:'1d'}));
app.use(session({store:new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true}),secret:process.env.SESSION_SECRET||process.env.NEXTAUTH_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*30}}));
app.use(passport.initialize());app.use(passport.session());
passport.serializeUser((u,d)=>d(null,u.id));
passport.deserializeUser(async(id,d)=>{try{const {rows}=await pool.query('select * from users where id=$1',[id]);d(null,rows[0]||false)}catch(e){d(e)}});
if(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET){passport.use(new GoogleStrategy({clientID:process.env.GOOGLE_CLIENT_ID,clientSecret:process.env.GOOGLE_CLIENT_SECRET,callbackURL:`${APP_URL}/auth/google/callback`},async(_a,_r,p,done)=>{try{const email=(p.emails?.[0]?.value||'').toLowerCase();if(!email)return done(null,false);let {rows}=await pool.query('select * from users where email=$1',[email]);let u=rows[0];if(!u){const id=crypto.randomUUID();const role=email===ADMIN_EMAIL?'admin':'user';await pool.query('insert into users(id,email,name,google_id,role,wallet_balance_toman,free_credit_granted) values($1,$2,$3,$4,$5,$6,true)',[id,email,p.displayName,p.id,role,FREE_CREDIT]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'free_credit',$3,$4)",[crypto.randomUUID(),id,FREE_CREDIT,'اعتبار هدیه شروع']);({rows}=await pool.query('select * from users where id=$1',[id]));u=rows[0]}else if(!u.google_id){await pool.query('update users set google_id=$1 where id=$2',[p.id,u.id])}done(null,u)}catch(e){done(e)}}));}

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toman(n){return Math.round(Number(n||0)).toLocaleString('fa-IR')+' تومان'}
function moneyUsd(n){return '$'+Number(n||0).toFixed(4)}
function csrf(req){if(!req.session.csrf)req.session.csrf=crypto.randomBytes(18).toString('hex');return req.session.csrf}
function checkCsrf(req,res,next){if(req.body?._csrf!==req.session.csrf)return res.status(403).send('Invalid request token');next()}
function base(title,body,{user=null,wide=false}={}){return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Bavaan AI</title><meta name="description" content="API مدل‌های هوش مصنوعی به صورت PAYG"><link rel="stylesheet" href="/static/style.css"></head><body>${body}</body></html>`}
function publicHeader(user){return `<header class="sitehead"><a href="/" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><nav><a href="/models">مدل‌ها</a><a href="/pricing">قیمت‌گذاری</a><a href="/docs">مستندات</a></nav><div class="actions">${user?`<a class="btn ghost" href="/dashboard">داشبورد</a>`:`<a class="btn ghost" href="/login">ورود</a><a class="btn primary" href="/register">شروع رایگان</a>`}</div></header>`}
function flash(req){const x=req.session.flash;delete req.session.flash;return x?`<div class="flash ${x.type||''}">${esc(x.text)}</div>`:''}
function guard(req,res,next){if(!req.user)return res.redirect('/login');if(req.user.status==='suspended')return res.status(403).send('Account suspended');next()}
function adminGuard(req,res,next){if(!req.user)return res.redirect('/login');if(req.user.role!=='admin')return res.redirect('/dashboard');next()}
function workspaceCards(ws){const m={api:[['ساخت API Key','برای اپ، تست یا محیط production'],['Quickstart','Python، Node و cURL'],['مدل‌ها','قیمت، قابلیت و route']],automation:[['کلید پروژه','برای هر مشتری یک کلید'],['n8n','الگوهای اتصال سریع'],['Telegram','ربات با یک API']],production:[['هزینه زنده','Cost و Revenue'],['Budget','کنترل مصرف کلیدها'],['Reliability','آماده برای fallback']],business:[['تولید محتوا','محصول، SEO و شبکه اجتماعی'],['تحلیل فایل','اسناد و PDF'],['Bulk','کارهای حجمی']],creative:[['تصویر','Text to Image'],['ویدئو','مدل‌های Video'],['تاریخچه','هزینه هر خروجی']],simple:[['گفت‌وگو','سؤال و جواب'],['نوشتن','متن و بازنویسی'],['ساخت تصویر','بدون درگیری با اسم مدل']]};return (m[ws]||m.simple).map(x=>`<div class="quick"><b>${x[0]}</b><small>${x[1]}</small></div>`).join('')}
function appShell(req,title,content){const u=req.user;const ws=u.workspace||'simple';const admin=u.role==='admin';const opts=Object.entries(WORKSPACES).map(([k,v])=>`<option value="${k}" ${ws===k?'selected':''}>${v}</option>`).join('');return base(title,`<div class="app"><aside><a href="/dashboard" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><div class="sidegroup"><span>فضای کار</span><a href="/dashboard">نمای کلی</a><a href="/dashboard/models">مدل‌ها</a><a href="/dashboard/api-keys">API Keys</a><a href="/dashboard/usage">مصرف و هزینه</a><a href="/dashboard/billing">کیف پول</a><a href="/dashboard/settings">تنظیمات</a></div>${admin?`<div class="sidegroup"><span>مدیریت</span><a href="/admin">داشبورد ادمین</a><a href="/admin/finance">مالی</a><a href="/admin/users">کاربران</a><a href="/admin/models">مدل‌ها و Providerها</a></div>`:''}</aside><main><div class="topbar"><form method="post" action="/workspace"><input type="hidden" name="_csrf" value="${csrf(req)}"><select class="workspace-select" name="workspace" onchange="this.form.submit()">${opts}</select></form><div class="topuser"><span>${esc(u.email)}</span><a href="/logout">خروج</a></div></div>${flash(req)}${content}</main></div>`,{user:u,wide:true})}

async function initDb(){await pool.query(`
create table if not exists users(id text primary key,email text unique not null,name text,password_hash text,google_id text unique,role text not null default 'user',status text not null default 'active',segment text,workspace text,onboarding_done boolean not null default false,wallet_balance_toman numeric(18,2) not null default 0,free_credit_granted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists api_keys(id text primary key,user_id text not null references users(id) on delete cascade,name text not null,prefix text not null,key_hash text unique not null,active boolean not null default true,spend_limit_toman numeric(18,2),total_spent_toman numeric(18,2) not null default 0,last_used_at timestamptz,created_at timestamptz not null default now());
create table if not exists providers(id text primary key,key text unique not null,name text not null,active boolean not null default true,balance_usd numeric(18,6),notes text,created_at timestamptz not null default now());
create table if not exists models(id text primary key,slug text unique not null,display_name text not null,provider_id text not null references providers(id),provider_model text not null,modality text not null default 'text',active boolean not null default false,input_cost_m_usd numeric(18,6) not null default 0,output_cost_m_usd numeric(18,6) not null default 0,markup_percent numeric(8,2) not null default 10,tags text not null default '',created_at timestamptz not null default now());
create table if not exists usage_records(id text primary key,user_id text not null references users(id),api_key_id text references api_keys(id),provider_id text not null references providers(id),model_id text not null references models(id),input_tokens int not null default 0,output_tokens int not null default 0,cost_usd numeric(18,8) not null default 0,charged_toman numeric(18,2) not null default 0,latency_ms int not null default 0,status text not null default 'success',request_id text,created_at timestamptz not null default now());
create table if not exists wallet_transactions(id text primary key,user_id text not null references users(id),type text not null,amount_toman numeric(18,2) not null,note text,created_at timestamptz not null default now());
create table if not exists provider_expenses(id text primary key,provider_id text not null references providers(id),amount_usd numeric(18,6) not null default 0,amount_toman numeric(18,2) not null default 0,note text,created_at timestamptz not null default now());
`);
 let {rows}=await pool.query("select id from providers where key='cloudflare'");let pid=rows[0]?.id;if(!pid){pid=crypto.randomUUID();await pool.query('insert into providers(id,key,name,notes) values($1,$2,$3,$4)',[pid,'cloudflare','Cloudflare AI Gateway','Unified Billing / Workers AI. Configure commercial rights before resale.'])}
 const seeds=[['gpt','GPT','openai/gpt-5.5','general,code'],['claude','Claude','anthropic/claude-sonnet-4-5','reasoning,writing,code'],['gemini','Gemini','google-ai-studio/gemini-2.5-flash','fast,business'],['deepseek','DeepSeek','deepseek/deepseek-chat','value,code'],['llama','Llama','@cf/meta/llama-3.3-70b-instruct-fp8-fast','open,fast']];
 for(const [slug,name,pm,tags] of seeds){await pool.query('insert into models(id,slug,display_name,provider_id,provider_model,tags,active) values($1,$2,$3,$4,$5,$6,false) on conflict(slug) do nothing',[crypto.randomUUID(),slug,name,pid,pm,tags])}
}

app.get('/',(req,res)=>res.send(base('همه مدل‌ها، یک API',`${publicHeader(req.user)}<section class="hero"><span class="badge">PAYG واقعی · بدون اشتراک ماهانه</span><h1>همه‌ی مدل‌های AI،<br><em>یک API و یک کیف پول.</em></h1><p>برای توسعه‌دهنده، آژانس، کسب‌وکار یا کسی که فقط می‌خواهد کارش را با AI انجام بدهد. محیط Bavaan خودش را با نوع استفاده‌ی شما هماهنگ می‌کند.</p><div class="actions"><a class="btn primary" href="/register">شروع رایگان + اعتبار هدیه</a><a class="btn ghost" href="/docs">دیدن مستندات</a></div><div class="proof"><span>✓ قیمت شفاف بر اساس مصرف</span><span>✓ OpenAI-compatible</span><span>✓ پرداخت ریالی</span></div></section><div class="wrap"><section class="section"><span class="badge">یک پلتفرم، چند Workspace</span><h2>لازم نیست همه یک داشبورد ببینند.</h2><p class="sectionlead">مثل Workspaceهای ابزارهای حرفه‌ای، Bavaan هم از همان شروع تجربه‌ی مناسب را بر اساس کاری که می‌خواهی انجام بدهی نشان می‌دهد.</p><div class="grid3"><div class="card"><h3>برای توسعه</h3><p>API Keys، مدل‌ها، latency، token usage، لاگ و نمونه‌کد.</p></div><div class="card"><h3>برای آژانس و اتوماسیون</h3><p>کلیدهای جدا، مصرف پروژه و الگوهای n8n و Telegram.</p></div><div class="card"><h3>برای کاربر غیر فنی</h3><p>به جای انتخاب مدل، فقط می‌گوید چه کاری می‌خواهد انجام دهد.</p></div></div></section><section class="section"><h2>مدل را انتخاب کن، یا اصلاً انتخاب نکن.</h2><p class="sectionlead">کاربر فنی کنترل کامل دارد؛ کاربر عادی فقط خروجی می‌خواهد.</p><div class="card"><div class="modelrow"><b>Claude</b><span class="modeltag">Reasoning</span><span>متن و کد</span><span>PAYG</span></div><div class="modelrow"><b>GPT</b><span class="modeltag">General</span><span>متن و ابزار</span><span>PAYG</span></div><div class="modelrow"><b>Gemini</b><span class="modeltag">Fast</span><span>متن و فایل</span><span>PAYG</span></div><div class="modelrow"><b>DeepSeek / Qwen / Llama</b><span class="modeltag">Value</span><span>اقتصادی</span><span>PAYG</span></div></div></section><section class="cta"><h2>با اعتبار هدیه شروع کن.</h2><p>ثبت‌نام کن، نوع استفاده‌ات را انتخاب کن و بدون خرید اولیه پلتفرم را تست کن.</p><a href="/register" class="btn primary">ساخت حساب رایگان</a></section></div><footer class="footer">Bavaan AI · ai.bavaan.ir</footer>`)));
app.get('/models',async(req,res)=>{const {rows}=await pool.query('select m.*,p.name provider_name from models m join providers p on p.id=m.provider_id order by m.display_name');res.send(base('مدل‌ها',`${publicHeader(req.user)}<div class="wrap section"><span class="badge">Model Catalog</span><h1>مدل‌ها</h1><p class="sectionlead">کاتالوگ یکپارچه. مدل‌ها بعد از نهایی‌شدن قیمت و upstream توسط ادمین فعال می‌شوند.</p><div class="card">${rows.map(m=>`<div class="modelrow"><b>${esc(m.display_name)}</b><span dir="ltr">${esc(m.slug)}</span><span>${esc(m.provider_name)}</span><span class="pill">${m.active?'فعال':'در حال آماده‌سازی'}</span></div>`).join('')}</div></div>`))});
app.get('/pricing',(req,res)=>res.send(base('قیمت‌گذاری',`${publicHeader(req.user)}<div class="wrap section"><span class="badge">قیمت‌گذاری ساده</span><h1>اشتراک نداریم. فقط مصرف.</h1><p class="sectionlead">کیف پول را شارژ می‌کنی و به اندازه‌ی مصرف پرداخت می‌کنی. قیمت هر مدل قبل از استفاده مشخص است.</p><div class="grid3"><div class="card"><h3>شروع</h3><h2>رایگان</h2><p>${toman(FREE_CREDIT)} اعتبار تست.</p></div><div class="card"><h3>PAYG</h3><h2>بدون پلن</h2><p>هزینه‌ی مدل + کارمزد شفاف، بدون تعهد ماهانه.</p></div><div class="card"><h3>مصرف بالا</h3><h2>Volume</h2><p>تخفیف بر اساس حجم مصرف، همچنان PAYG.</p></div></div></div>`)));
app.get('/docs',(req,res)=>res.send(base('مستندات',`${publicHeader(req.user)}<div class="doclayout"><aside class="docsnav"><b>مستندات</b><a href="#start">شروع سریع</a><a href="#auth">API Key</a><a href="#billing">Billing</a></aside><article class="docs"><span class="badge">Docs</span><h1>یک API شبیه OpenAI</h1><p class="sectionlead">برای مهاجرت معمولاً فقط Base URL و API Key را عوض می‌کنی.</p><h2 id="start">شروع سریع</h2><pre class="code">curl ${APP_URL}/api/v1/chat/completions \\
-H "Authorization: Bearer bv_YOUR_KEY" \\
-H "Content-Type: application/json" \\
-d '{"model":"gemini","messages":[{"role":"user","content":"سلام"}]}'</pre><h2 id="auth">API Key</h2><p>از Dashboard ← API Keys یک کلید بساز. مقدار کامل فقط یک بار نمایش داده می‌شود.</p><h2 id="billing">شفافیت هزینه</h2><p>Input، Output، هزینه upstream، مبلغ کسرشده، latency و request ID برای هر درخواست ثبت می‌شود.</p></article></div>`)));

app.get('/register',(req,res)=>{if(req.user)return res.redirect('/dashboard');res.send(base('ثبت‌نام',`<div class="authpage"><div class="authcard"><a href="/" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><h1>حسابت رو بساز</h1><p class="sub">بدون خرید اولیه، با ${toman(FREE_CREDIT)} اعتبار هدیه.</p>${flash(req)}<form class="stack" method="post" action="/register"><input type="hidden" name="_csrf" value="${csrf(req)}"><input name="name" placeholder="نام"><input name="email" type="email" dir="ltr" placeholder="Email" required><input name="password" type="password" dir="ltr" minlength="8" placeholder="رمز عبور، حداقل ۸ کاراکتر" required><button class="btn primary">ساخت حساب</button></form>${process.env.GOOGLE_CLIENT_ID?`<div class="or">یا</div><a class="btn ghost wide" href="/auth/google">ثبت‌نام با Google</a>`:''}<p class="sub">حساب داری؟ <a href="/login">ورود</a></p></div></div>`))});
app.post('/register',checkCsrf,async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),pass=String(req.body.password||'');if(!email||pass.length<8){req.session.flash={type:'error',text:'ایمیل معتبر و رمز حداقل ۸ کاراکتری لازم است.'};return res.redirect('/register')}const ex=await pool.query('select 1 from users where email=$1',[email]);if(ex.rowCount){req.session.flash={type:'error',text:'این ایمیل قبلاً ثبت شده.'};return res.redirect('/register')}const id=crypto.randomUUID(),hash=await bcrypt.hash(pass,12),role=email===ADMIN_EMAIL?'admin':'user';await pool.query('insert into users(id,email,name,password_hash,role,wallet_balance_toman,free_credit_granted) values($1,$2,$3,$4,$5,$6,true)',[id,email,req.body.name||null,hash,role,FREE_CREDIT]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'free_credit',$3,$4)",[crypto.randomUUID(),id,FREE_CREDIT,'اعتبار هدیه شروع']);const {rows}=await pool.query('select * from users where id=$1',[id]);req.login(rows[0],e=>e?res.status(500).send('Login failed'):res.redirect('/onboarding'))});
app.get('/login',(req,res)=>{if(req.user)return res.redirect('/dashboard');res.send(base('ورود',`<div class="authpage"><div class="authcard"><a href="/" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><h1>خوش برگشتی</h1>${flash(req)}<form class="stack" method="post" action="/login"><input type="hidden" name="_csrf" value="${csrf(req)}"><input name="email" type="email" dir="ltr" placeholder="Email" required><input name="password" type="password" dir="ltr" placeholder="رمز عبور" required><button class="btn primary">ورود</button></form>${process.env.GOOGLE_CLIENT_ID?`<div class="or">یا</div><a class="btn ghost wide" href="/auth/google">ورود با Google</a>`:''}<p class="sub">حساب نداری؟ <a href="/register">ثبت‌نام</a></p></div></div>`))});
app.post('/login',checkCsrf,async(req,res)=>{const {rows}=await pool.query('select * from users where email=$1',[String(req.body.email||'').toLowerCase()]);const u=rows[0];if(!u?.password_hash||!(await bcrypt.compare(String(req.body.password||''),u.password_hash))){req.session.flash={type:'error',text:'ایمیل یا رمز عبور درست نیست.'};return res.redirect('/login')}req.login(u,e=>e?res.status(500).send('Login failed'):res.redirect(u.onboarding_done?'/dashboard':'/onboarding'))});
app.get('/auth/google',(req,res,next)=>process.env.GOOGLE_CLIENT_ID?passport.authenticate('google',{scope:['profile','email']})(req,res,next):res.redirect('/login'));
app.get('/auth/google/callback',(req,res,next)=>passport.authenticate('google',{failureRedirect:'/login'})(req,res,()=>res.redirect(req.user.onboarding_done?'/dashboard':'/onboarding')));
app.get('/logout',(req,res)=>req.logout(()=>res.redirect('/')));

app.get('/onboarding',guard,(req,res)=>res.send(base('شروع',`<div class="onboard"><span class="badge">کمتر از یک دقیقه</span><h1>بیشتر برای چه کاری می‌خوای از Bavaan استفاده کنی؟</h1><p class="sub">اسم دسته‌ها مهم نیست؛ چیزی رو انتخاب کن که شبیه خودته. بعداً هم می‌تونی عوضش کنی.</p><form method="post" action="/onboarding"><input type="hidden" name="_csrf" value="${csrf(req)}"><div class="choicegrid">${Object.entries(SEGMENTS).map(([k,s])=>`<label class="choice"><input type="radio" name="segment" value="${k}" required><b>${s.title}</b><span>${s.desc}</span></label>`).join('')}</div><button class="btn primary big">ورود به فضای من</button></form></div>`)));
app.post('/onboarding',guard,checkCsrf,async(req,res)=>{const s=SEGMENTS[req.body.segment];if(!s)return res.redirect('/onboarding');await pool.query('update users set segment=$1,workspace=$2,onboarding_done=true,updated_at=now() where id=$3',[req.body.segment,s.workspace,req.user.id]);req.user.segment=req.body.segment;req.user.workspace=s.workspace;req.user.onboarding_done=true;res.redirect('/dashboard')});
app.post('/workspace',guard,checkCsrf,async(req,res)=>{if(!WORKSPACES[req.body.workspace])return res.redirect('/dashboard');await pool.query('update users set workspace=$1,updated_at=now() where id=$2',[req.body.workspace,req.user.id]);req.user.workspace=req.body.workspace;res.redirect(req.get('referer')||'/dashboard')});

app.get('/dashboard',guard,async(req,res)=>{if(!req.user.onboarding_done)return res.redirect('/onboarding');const q=await pool.query('select coalesce(sum(charged_toman),0) spend,count(*) requests from usage_records where user_id=$1',[req.user.id]);const k=await pool.query('select count(*) c from api_keys where user_id=$1 and active=true',[req.user.id]);const ws=req.user.workspace||'simple';const x=q.rows[0];res.send(appShell(req,'داشبورد',`<div class="dash"><div class="dashhead"><div><h1>سلام ${esc(req.user.name||'')}</h1><div class="sub">Workspace: ${WORKSPACES[ws]}</div></div></div><div class="stats"><div class="stat"><span>موجودی کیف پول</span><b>${toman(req.user.wallet_balance_toman)}</b></div><div class="stat"><span>مصرف کل</span><b>${toman(x.spend)}</b></div><div class="stat"><span>Request</span><b>${Number(x.requests).toLocaleString('fa-IR')}</b></div><div class="stat"><span>API Key فعال</span><b>${Number(k.rows[0].c).toLocaleString('fa-IR')}</b></div></div><div class="workspacehero"><div class="card hero-card"><span class="badge">فضای پیشنهادی تو</span><h2>${WORKSPACES[ws]}</h2><p>ابزارها بر اساس نوع استفاده‌ات مرتب شده‌اند. هر وقت خواستی از بالای صفحه Workspace را عوض کن.</p><div class="quickgrid">${workspaceCards(ws)}</div></div><div class="card"><h3>هزینه‌ی این حساب</h3><b class="huge">${toman(x.spend)}</b><p>بر اساس مصرف واقعی API</p></div></div></div>`))});
app.get('/dashboard/models',guard,async(req,res)=>{const {rows}=await pool.query('select m.*,p.name provider_name from models m join providers p on p.id=m.provider_id order by m.display_name');res.send(appShell(req,'مدل‌ها',`<div class="dash"><h1>مدل‌ها</h1><p class="sub">شناسه پایدار Bavaan و upstream پشت آن.</p><div class="card"><table class="table"><tr><th>مدل</th><th>شناسه API</th><th>Provider</th><th>وضعیت</th></tr>${rows.map(m=>`<tr><td><b>${esc(m.display_name)}</b></td><td dir="ltr">${esc(m.slug)}</td><td>${esc(m.provider_name)}</td><td><span class="pill">${m.active?'فعال':'غیرفعال'}</span></td></tr>`).join('')}</table></div></div>`))});
app.get('/dashboard/api-keys',guard,async(req,res)=>{const {rows}=await pool.query('select * from api_keys where user_id=$1 order by created_at desc',[req.user.id]);const raw=req.session.newKey;delete req.session.newKey;res.send(appShell(req,'API Keys',`<div class="dash"><div class="dashhead"><div><h1>API Keys</h1><p class="sub">برای پروژه‌ها یا مشتری‌ها کلید جدا بساز.</p></div><form method="post" action="/dashboard/api-keys"><input type="hidden" name="_csrf" value="${csrf(req)}"><button class="btn primary">ساخت API Key</button></form></div>${raw?`<div class="secretbox"><b>این کلید فقط همین یک‌بار نمایش داده می‌شود:</b><code>${esc(raw)}</code></div>`:''}<div class="card"><table class="table"><tr><th>نام</th><th>کلید</th><th>مصرف</th><th>آخرین استفاده</th></tr>${rows.map(k=>`<tr><td>${esc(k.name)}</td><td dir="ltr">${esc(k.prefix)}••••••</td><td>${toman(k.total_spent_toman)}</td><td>${k.last_used_at?new Date(k.last_used_at).toLocaleString('fa-IR'):'—'}</td></tr>`).join('')}</table></div></div>`))});
app.post('/dashboard/api-keys',guard,checkCsrf,async(req,res)=>{const raw='bv_'+crypto.randomBytes(24).toString('hex'),hash=crypto.createHash('sha256').update(raw).digest('hex');await pool.query('insert into api_keys(id,user_id,name,prefix,key_hash) values($1,$2,$3,$4,$5)',[crypto.randomUUID(),req.user.id,'کلید '+new Date().toLocaleDateString('fa-IR'),raw.slice(0,11),hash]);req.session.newKey=raw;res.redirect('/dashboard/api-keys')});
app.get('/dashboard/usage',guard,async(req,res)=>{const {rows}=await pool.query('select u.*,m.display_name from usage_records u join models m on m.id=u.model_id where u.user_id=$1 order by u.created_at desc limit 100',[req.user.id]);res.send(appShell(req,'مصرف و هزینه',`<div class="dash"><h1>مصرف و هزینه</h1><p class="sub">شفافیت request-level.</p><div class="card"><table class="table"><tr><th>زمان</th><th>مدل</th><th>Input / Output</th><th>Latency</th><th>هزینه</th></tr>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('fa-IR')}</td><td>${esc(x.display_name)}</td><td>${x.input_tokens.toLocaleString('fa-IR')} / ${x.output_tokens.toLocaleString('fa-IR')}</td><td>${x.latency_ms}ms</td><td>${toman(x.charged_toman)}</td></tr>`).join('')}</table></div></div>`))});
app.get('/dashboard/billing',guard,async(req,res)=>{const {rows}=await pool.query('select * from wallet_transactions where user_id=$1 order by created_at desc limit 100',[req.user.id]);res.send(appShell(req,'کیف پول',`<div class="dash"><h1>کیف پول</h1><div class="stats"><div class="stat"><span>موجودی</span><b>${toman(req.user.wallet_balance_toman)}</b></div><div class="stat"><span>مدل پرداخت</span><b>PAYG</b></div></div><div class="card mt"><h3>گردش کیف پول</h3><table class="table">${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('fa-IR')}</td><td>${esc(x.note||x.type)}</td><td dir="ltr" class="${Number(x.amount_toman)>=0?'metricgood':'metricbad'}">${toman(x.amount_toman)}</td></tr>`).join('')}</table></div></div>`))});
app.get('/dashboard/settings',guard,(req,res)=>res.send(appShell(req,'تنظیمات',`<div class="dash"><h1>تنظیمات</h1><div class="card"><h3>نوع استفاده‌ی اصلی</h3><p class="sub">این انتخاب فقط پیشنهادهای Workspace را تنظیم می‌کند؛ هر زمان قابل تغییر است.</p><form method="post" action="/dashboard/settings" class="stack narrow"><input type="hidden" name="_csrf" value="${csrf(req)}"><select name="segment">${Object.entries(SEGMENTS).map(([k,s])=>`<option value="${k}" ${req.user.segment===k?'selected':''}>${s.title}</option>`).join('')}</select><button class="btn primary">ذخیره و تغییر Workspace پیشنهادی</button></form></div></div>`)));
app.post('/dashboard/settings',guard,checkCsrf,async(req,res)=>{const s=SEGMENTS[req.body.segment];if(s){await pool.query('update users set segment=$1,workspace=$2,updated_at=now() where id=$3',[req.body.segment,s.workspace,req.user.id]);req.user.segment=req.body.segment;req.user.workspace=s.workspace}res.redirect('/dashboard/settings')});

app.get('/admin',adminGuard,async(req,res)=>{const [users,usage,exp,wallet,segments,topModels]=await Promise.all([pool.query('select count(*) c from users'),pool.query('select count(*) requests,coalesce(sum(charged_toman),0) revenue,coalesce(sum(cost_usd),0) cost_usd from usage_records'),pool.query('select coalesce(sum(amount_toman),0) c from provider_expenses'),pool.query('select coalesce(sum(wallet_balance_toman),0) c from users'),pool.query("select coalesce(segment,'unset') segment,count(*) c from users group by segment order by c desc"),pool.query('select m.display_name,count(*) requests,coalesce(sum(u.charged_toman),0) revenue,coalesce(sum(u.cost_usd),0) cost_usd from usage_records u join models m on m.id=u.model_id group by m.display_name order by revenue desc limit 8')]);const revenue=Number(usage.rows[0].revenue),expense=Number(exp.rows[0].c),margin=revenue-expense;let insights=[];if(revenue>0&&margin/revenue<.12)insights.push('حاشیه سود ثبت‌شده زیر ۱۲٪ است؛ markup یا route مدل‌های پرترافیک را بررسی کن.');if(Number(wallet.rows[0].c)>revenue*2&&revenue>0)insights.push('تعهد کیف پول کاربران نسبت به درآمد ثبت‌شده بالاست؛ provider liquidity را کنترل کن.');if(!insights.length)insights.push('هنوز هشدار مالی جدی از داده‌های ثبت‌شده دیده نمی‌شود.');res.send(appShell(req,'ادمین',`<div class="dash"><h1>مرکز فرمان Bavaan</h1><p class="sub">رشد، مصرف، مالی و سلامت پلتفرم.</p><div class="stats"><div class="stat"><span>کاربر</span><b>${Number(users.rows[0].c).toLocaleString('fa-IR')}</b></div><div class="stat"><span>درآمد Usage</span><b>${toman(revenue)}</b></div><div class="stat"><span>هزینه Provider ثبت‌شده</span><b>${toman(expense)}</b></div><div class="stat"><span>Gross Result</span><b class="${margin>=0?'metricgood':'metricbad'}">${toman(margin)}</b></div></div><div class="admin-grid"><div class="card"><h3>Insightهای عملیاتی</h3>${insights.map(x=>`<p>• ${esc(x)}</p>`).join('')}<p>• تعهد کیف پول کاربران: <b>${toman(wallet.rows[0].c)}</b></p></div><div class="card"><h3>توزیع نوع استفاده</h3>${segments.rows.map(x=>`<div class="barline"><span>${esc(x.segment)}</span><b>${Number(x.c).toLocaleString('fa-IR')}</b></div>`).join('')}</div></div><div class="card mt"><h3>مدل‌های درآمدساز</h3><table class="table"><tr><th>مدل</th><th>Request</th><th>Revenue</th><th>Upstream Cost</th></tr>${topModels.rows.map(x=>`<tr><td>${esc(x.display_name)}</td><td>${x.requests}</td><td>${toman(x.revenue)}</td><td>${moneyUsd(x.cost_usd)}</td></tr>`).join('')}</table></div></div>`))});
app.get('/admin/users',adminGuard,async(req,res)=>{const {rows}=await pool.query("select u.*,count(distinct r.id) requests,count(distinct k.id) keys from users u left join usage_records r on r.user_id=u.id left join api_keys k on k.user_id=u.id group by u.id order by u.created_at desc limit 300");res.send(appShell(req,'کاربران',`<div class="dash"><h1>کاربران و کیف پول</h1><div class="card"><table class="table"><tr><th>کاربر</th><th>نوع</th><th>موجودی</th><th>Request / Keys</th><th>اصلاح کیف پول</th></tr>${rows.map(u=>`<tr><td><b>${esc(u.name||'—')}</b><br><small>${esc(u.email)}</small></td><td>${esc(u.segment||'—')}</td><td>${toman(u.wallet_balance_toman)}</td><td>${u.requests} / ${u.keys}</td><td><form class="inline" method="post" action="/admin/users/${u.id}/wallet"><input type="hidden" name="_csrf" value="${csrf(req)}"><input name="amount" class="mini" placeholder="± تومان"><button class="btn ghost">اعمال</button></form></td></tr>`).join('')}</table></div></div>`))});
app.post('/admin/users/:id/wallet',adminGuard,checkCsrf,async(req,res)=>{const amount=Number(req.body.amount);if(Number.isFinite(amount)&&amount!==0){await pool.query('begin');try{await pool.query('update users set wallet_balance_toman=wallet_balance_toman+$1 where id=$2',[amount,req.params.id]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'admin_adjustment',$3,$4)",[crypto.randomUUID(),req.params.id,amount,'اصلاح موجودی توسط ادمین']);await pool.query('commit')}catch(e){await pool.query('rollback');throw e}}res.redirect('/admin/users')});
app.get('/admin/finance',adminGuard,async(req,res)=>{const [providers,expenses,usage,wallet]=await Promise.all([pool.query('select * from providers order by name'),pool.query('select e.*,p.name provider_name from provider_expenses e join providers p on p.id=e.provider_id order by e.created_at desc limit 100'),pool.query('select coalesce(sum(charged_toman),0) revenue,coalesce(sum(cost_usd),0) cost from usage_records'),pool.query('select coalesce(sum(wallet_balance_toman),0) c from users')]);const expT=expenses.rows.reduce((s,x)=>s+Number(x.amount_toman),0);res.send(appShell(req,'مالی',`<div class="dash"><h1>مالی</h1><p class="sub">Provider spend، درآمد مصرف و تعهد کیف پول.</p><div class="financegrid"><div class="stat"><span>درآمد Usage</span><b>${toman(usage.rows[0].revenue)}</b></div><div class="stat"><span>Provider Expense</span><b>${toman(expT)}</b></div><div class="stat"><span>Wallet Liability</span><b>${toman(wallet.rows[0].c)}</b></div></div><div class="admin-grid mt"><div class="card"><h3>ثبت خرید / شارژ Provider</h3><form class="stack" method="post" action="/admin/finance"><input type="hidden" name="_csrf" value="${csrf(req)}"><select name="provider_id">${providers.rows.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><input name="amount_usd" placeholder="مبلغ دلار"><input name="amount_toman" placeholder="معادل تومان"><input name="note" placeholder="یادداشت"><button class="btn primary">ثبت هزینه</button></form></div><div class="card"><h3>آخرین هزینه‌ها</h3>${expenses.rows.slice(0,8).map(x=>`<div class="barline"><span>${esc(x.provider_name)}</span><b>${moneyUsd(x.amount_usd)} · ${toman(x.amount_toman)}</b></div>`).join('')}</div></div></div>`))});
app.post('/admin/finance',adminGuard,checkCsrf,async(req,res)=>{await pool.query('insert into provider_expenses(id,provider_id,amount_usd,amount_toman,note) values($1,$2,$3,$4,$5)',[crypto.randomUUID(),req.body.provider_id,Number(req.body.amount_usd||0),Number(req.body.amount_toman||0),req.body.note||null]);res.redirect('/admin/finance')});
app.get('/admin/models',adminGuard,async(req,res)=>{const [providers,models]=await Promise.all([pool.query('select * from providers order by name'),pool.query('select m.*,p.name provider_name from models m join providers p on p.id=m.provider_id order by m.display_name')]);res.send(appShell(req,'مدل‌ها و Providerها',`<div class="dash"><h1>مدل‌ها و Providerها</h1><div class="grid3">${providers.rows.map(p=>`<div class="card"><span class="pill">${p.active?'فعال':'غیرفعال'}</span><h3>${esc(p.name)}</h3><p>Balance: ${p.balance_usd?moneyUsd(p.balance_usd):'ثبت نشده'}</p></div>`).join('')}</div><div class="card mt"><table class="table"><tr><th>مدل</th><th>upstream</th><th>Input $/M</th><th>Output $/M</th><th>Markup</th><th>فعال</th></tr>${models.rows.map(m=>`<tr><td>${esc(m.display_name)}</td><td dir="ltr">${esc(m.provider_model)}</td><td colspan="4"><form class="inline" method="post" action="/admin/models/${m.id}"><input type="hidden" name="_csrf" value="${csrf(req)}"><input class="mini" name="input_cost" value="${m.input_cost_m_usd}"><input class="mini" name="output_cost" value="${m.output_cost_m_usd}"><input class="mini" name="markup" value="${m.markup_percent}"><label><input type="checkbox" name="active" ${m.active?'checked':''}> فعال</label><button class="btn ghost">ذخیره</button></form></td></tr>`).join('')}</table></div></div>`))});
app.post('/admin/models/:id',adminGuard,checkCsrf,async(req,res)=>{await pool.query('update models set input_cost_m_usd=$1,output_cost_m_usd=$2,markup_percent=$3,active=$4 where id=$5',[Number(req.body.input_cost||0),Number(req.body.output_cost||0),Number(req.body.markup||0),!!req.body.active,req.params.id]);res.redirect('/admin/models')});

app.post('/api/v1/chat/completions',async(req,res)=>{const started=Date.now();const raw=(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!raw.startsWith('bv_'))return res.status(401).json({error:{message:'Invalid API key'}});const hash=crypto.createHash('sha256').update(raw).digest('hex');const kq=await pool.query('select k.*,u.wallet_balance_toman,u.status from api_keys k join users u on u.id=k.user_id where k.key_hash=$1 and k.active=true',[hash]);const key=kq.rows[0];if(!key||key.status!=='active')return res.status(401).json({error:{message:'Invalid API key'}});if(req.body.stream)return res.status(400).json({error:{message:'stream=true is not enabled in the first provider adapter yet'}});const mq=await pool.query('select m.*,p.key provider_key,p.id provider_id from models m join providers p on p.id=m.provider_id where m.slug=$1 and m.active=true',[String(req.body.model||'')]);const model=mq.rows[0];if(!model)return res.status(404).json({error:{message:'Unknown or inactive model'}});if(Number(key.wallet_balance_toman)<=0)return res.status(402).json({error:{message:'Insufficient balance'}});if(model.provider_key!=='cloudflare')return res.status(501).json({error:{message:'Provider adapter not configured'}});const account=process.env.CLOUDFLARE_ACCOUNT_ID,token=process.env.CLOUDFLARE_API_TOKEN;if(!account||!token)return res.status(503).json({error:{message:'Provider credentials are not configured yet'}});
 const upstream=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/ai/v1/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','cf-aig-gateway-id':process.env.CLOUDFLARE_GATEWAY_ID||'default'},body:JSON.stringify({...req.body,model:model.provider_model,stream:false})});const data=await upstream.json();if(!upstream.ok)return res.status(upstream.status).json(data);const input=Number(data?.usage?.prompt_tokens||data?.usage?.input_tokens||0),output=Number(data?.usage?.completion_tokens||data?.usage?.output_tokens||0);const costUsd=input/1e6*Number(model.input_cost_m_usd)+output/1e6*Number(model.output_cost_m_usd);const charge=Math.max(1,Math.ceil(costUsd*USD_TO_TOMAN*(1+Number(model.markup_percent)/100)));const uid=crypto.randomUUID();await pool.query('begin');try{const bal=await pool.query('select wallet_balance_toman from users where id=$1 for update',[key.user_id]);if(Number(bal.rows[0].wallet_balance_toman)<charge){await pool.query('rollback');return res.status(402).json({error:{message:'Insufficient balance'}})}await pool.query('update users set wallet_balance_toman=wallet_balance_toman-$1 where id=$2',[charge,key.user_id]);await pool.query('update api_keys set total_spent_toman=total_spent_toman+$1,last_used_at=now() where id=$2',[charge,key.id]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'usage',$3,$4)",[crypto.randomUUID(),key.user_id,-charge,`${model.display_name} API usage`]);await pool.query("insert into usage_records(id,user_id,api_key_id,provider_id,model_id,input_tokens,output_tokens,cost_usd,charged_toman,latency_ms,status,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'success',$11)",[uid,key.user_id,key.id,model.provider_id,model.id,input,output,costUsd,charge,Date.now()-started,data?.id||null]);await pool.query('commit')}catch(e){await pool.query('rollback');throw e}res.json({...data,model:model.slug,bavaan:{charged_toman:charge}})});
app.get('/api/v1/models',async(req,res)=>{const {rows}=await pool.query('select slug,display_name,modality,tags from models where active=true order by display_name');res.json({object:'list',data:rows.map(m=>({id:m.slug,object:'model',name:m.display_name,modality:m.modality,tags:m.tags.split(',').filter(Boolean)}))})});
app.get('/healthz',(_req,res)=>res.json({ok:true}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).send(base('خطا','<div class="authpage"><div class="authcard"><h1>خطایی پیش آمد</h1><p class="sub">دوباره تلاش کن یا با پشتیبانی تماس بگیر.</p></div></div>'))});

initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Bavaan AI listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
