const express=require('express');
const session=require('express-session');
const pgSession=require('connect-pg-simple')(session);
const passport=require('passport');
const GoogleStrategy=require('passport-google-oauth20').Strategy;
const bcrypt=require('bcryptjs');
const helmet=require('helmet');
const crypto=require('crypto');
const {Pool}=require('pg');

const app=express();
const PORT=Number(process.env.PORT||3000);
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const FREE_CREDIT=Number(process.env.FREE_CREDIT_TOMAN||50000);
const USD_TO_TOMAN=Number(process.env.USD_TO_TOMAN||100000);
const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'').toLowerCase();
const APP_URL=process.env.APP_URL||'https://ai.bavaan.ir';
const ASSET_VERSION=process.env.ASSET_VERSION||String(Date.now());
const CLOUDFLARE_GATEWAY_ID=(process.env.CLOUDFLARE_GATEWAY_ID||'default').trim()||'default';
const SEGMENTS={
 developer:{workspace:'api',title:'می‌خوام API رو به اپ یا سایتم وصل کنم',desc:'کلید API، مدل‌ها، لاگ مصرف و مستندات فنی.'},
 agency:{workspace:'automation',title:'برای مشتری‌هام ربات و اتوماسیون می‌سازم',desc:'پروژه‌ها، کلیدهای جدا، n8n، تلگرام و مصرف هر مشتری.'},
 startup:{workspace:'production',title:'یک محصول AI دارم و مصرف production برام مهمه',desc:'پایداری، بودجه، route جایگزین و تحلیل هزینه.'},
 business:{workspace:'business',title:'برای کسب‌وکارم محتوا و کارهای تکراری می‌خوام',desc:'تولید محتوا، تحلیل فایل و کارهای حجمی بدون درگیری با مدل.'},
 creator:{workspace:'creative',title:'بیشتر با تصویر، ویدئو و محتوای خلاق کار می‌کنم',desc:'فضای خلاق با تمرکز روی هزینه هر خروجی.'},
 everyday:{workspace:'simple',title:'فقط می‌خوام AI کارم رو انجام بده؛ اسم مدل مهم نیست',desc:'به جای انتخاب مدل، فقط کاری که می‌خوای انجام بدی رو انتخاب کن.'}
};
const WORKSPACES={api:'توسعه و API',automation:'اتوماسیون و مشتری',production:'محصول و Production',business:'کسب‌وکار',creative:'استودیوی خلاق',simple:'استفاده روزمره'};

app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.urlencoded({extended:true,limit:'1mb'}));
app.use(express.json({limit:'2mb'}));
app.use('/static',express.static('public',{maxAge:'5m',etag:true}));
app.use(session({store:new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true}),secret:process.env.SESSION_SECRET||process.env.NEXTAUTH_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*30}}));
app.use(passport.initialize());app.use(passport.session());
passport.serializeUser((u,d)=>d(null,u.id));
passport.deserializeUser(async(id,d)=>{try{const {rows}=await pool.query('select * from users where id=$1',[id]);d(null,rows[0]||false)}catch(e){d(e)}});
if(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET){passport.use(new GoogleStrategy({clientID:process.env.GOOGLE_CLIENT_ID,clientSecret:process.env.GOOGLE_CLIENT_SECRET,callbackURL:`${APP_URL}/auth/google/callback`},async(_a,_r,p,done)=>{try{const email=(p.emails?.[0]?.value||'').toLowerCase();if(!email)return done(null,false);let {rows}=await pool.query('select * from users where email=$1',[email]);let u=rows[0];if(!u){const id=crypto.randomUUID();const role=email===ADMIN_EMAIL?'admin':'user';await pool.query('insert into users(id,email,name,google_id,role,wallet_balance_toman,free_credit_granted) values($1,$2,$3,$4,$5,$6,true)',[id,email,p.displayName,p.id,role,FREE_CREDIT]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'free_credit',$3,$4)",[crypto.randomUUID(),id,FREE_CREDIT,'اعتبار هدیه شروع']);({rows}=await pool.query('select * from users where id=$1',[id]));u=rows[0]}else if(!u.google_id){await pool.query('update users set google_id=$1 where id=$2',[p.id,u.id])}done(null,u)}catch(e){done(e)}}));}

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toman(n){return Math.round(Number(n||0)).toLocaleString('fa-IR')+' تومان'}
function moneyUsd(n){return '$'+Number(n||0).toFixed(4)}
function csrf(req){if(!req.session.csrf)req.session.csrf=crypto.randomBytes(18).toString('hex');return req.session.csrf}
function checkCsrf(req,res,next){if(req.body?._csrf!==req.session.csrf)return res.status(403).send('Invalid request token');next()}
function base(title,body,{user=null,wide=false}={}){return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Bavaan AI</title><meta name="description" content="API مدل‌های هوش مصنوعی به صورت PAYG"><link rel="stylesheet" href="/static/style.css?v=${esc(ASSET_VERSION)}"></head><body>${body}</body></html>`}
function publicHeader(user){return `<header class="sitehead"><a href="/" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><nav><a href="/models">مدل‌ها</a><a href="/pricing">قیمت‌گذاری</a><a href="/docs">مستندات</a></nav><div class="actions">${user?`<a class="btn ghost" href="/dashboard">داشبورد</a>`:`<a class="btn ghost" href="/login">ورود</a><a class="btn primary" href="/register">شروع رایگان</a>`}</div></header>`}
function flash(req){const x=req.session.flash;delete req.session.flash;return x?`<div class="flash ${x.type||''}">${esc(x.text)}</div>`:''}
function guard(req,res,next){if(!req.user)return res.redirect('/login');if(req.user.status==='suspended')return res.status(403).send('Account suspended');next()}
function adminGuard(req,res,next){if(!req.user)return res.redirect('/login');if(req.user.role!=='admin')return res.redirect('/dashboard');next()}
function workspaceCards(ws){const m={api:[['ساخت API Key','برای اپ، تست یا محیط production'],['Quickstart','Python، Node و cURL'],['مدل‌ها','قیمت، قابلیت و route']],automation:[['کلید پروژه','برای هر مشتری یک کلید'],['n8n','الگوهای اتصال سریع'],['Telegram','ربات با یک API']],production:[['هزینه زنده','Cost و Revenue'],['Budget','کنترل مصرف کلیدها'],['Reliability','آماده برای fallback']],business:[['تولید محتوا','محصول، SEO و شبکه اجتماعی'],['تحلیل فایل','اسناد و PDF'],['Bulk','کارهای حجمی']],creative:[['تصویر','Text to Image'],['ویدئو','مدل‌های Video'],['تاریخچه','هزینه هر خروجی']],simple:[['گفت‌وگو','سؤال و جواب'],['نوشتن','متن و بازنویسی'],['ساخت تصویر','بدون درگیری با اسم مدل']]};return (m[ws]||m.simple).map(x=>`<div class="quick"><b>${x[0]}</b><small>${x[1]}</small></div>`).join('')}
function workspaceMenu(ws){
 const menus={
  api:[['/dashboard','نمای کلی'],['/dashboard/ai','Playground'],['/dashboard/api-keys','کلیدهای API'],['/dashboard/models','مدل‌ها'],['/dashboard/usage','مصرف و لاگ‌ها']],
  automation:[['/dashboard','نمای کلی'],['/dashboard/ai','آزمایش AI'],['/dashboard/api-keys','کلیدهای پروژه'],['/dashboard/usage','مصرف پروژه‌ها']],
  production:[['/dashboard','نمای کلی'],['/dashboard/ai','Playground'],['/dashboard/usage','پایش مصرف'],['/dashboard/models','مدل‌ها'],['/dashboard/api-keys','کلیدهای Production']],
  business:[['/dashboard','خانه'],['/dashboard/ai?mode=write','تولید محتوا'],['/dashboard/ai?mode=summarize','خلاصه و تحلیل'],['/dashboard/ai?mode=translate','ترجمه'],['/dashboard/usage','مصرف من']],
  creative:[['/dashboard','استودیو'],['/dashboard/ai?mode=creative','دستیار خلاق'],['/dashboard/usage','تاریخچه هزینه']],
  simple:[['/dashboard','خانه'],['/dashboard/ai','گفت‌وگو با AI'],['/dashboard/ai?mode=write','نوشتن'],['/dashboard/ai?mode=translate','ترجمه'],['/dashboard/ai?mode=summarize','خلاصه‌سازی'],['/dashboard/usage','مصرف من']]
 };
 return menus[ws]||menus.simple;
}
function appShell(req,title,content){
 const u=req.user;const ws=u.workspace||'simple';const admin=u.role==='admin';
 const opts=Object.entries(WORKSPACES).map(([k,v])=>`<option value="${k}" ${ws===k?'selected':''}>${v}</option>`).join('');
 const links=workspaceMenu(ws).map(([href,label])=>`<a href="${href}">${label}</a>`).join('');
 return base(title,`<div class="app"><aside><a href="/dashboard" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><div class="workspace-name">${WORKSPACES[ws]}</div><div class="sidegroup"><span>فضای کار</span>${links}<a href="/dashboard/billing">کیف پول</a><a href="/dashboard/settings">تنظیمات</a></div>${admin?`<div class="sidegroup"><span>مدیریت</span><a href="/admin">داشبورد ادمین</a><a href="/admin/finance">مالی</a><a href="/admin/users">کاربران</a><a href="/admin/models">مدل‌ها و Providerها</a></div>`:''}</aside><main><div class="topbar"><form method="post" action="/workspace"><input type="hidden" name="_csrf" value="${csrf(req)}"><select class="workspace-select" name="workspace" onchange="this.form.submit()">${opts}</select></form><div class="topuser"><span>${esc(u.email)}</span><a href="/logout">خروج</a></div></div><nav class="mobile-workspace-nav" aria-label="منوی فضای کار">${links}<a href="/dashboard/billing">کیف پول</a></nav>${flash(req)}${content}</main></div>`,{user:u,wide:true})
}

async function initDb(){await pool.query(`
create table if not exists users(id text primary key,email text unique not null,name text,password_hash text,google_id text unique,role text not null default 'user',status text not null default 'active',segment text,workspace text,onboarding_done boolean not null default false,wallet_balance_toman numeric(18,2) not null default 0,free_credit_granted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists api_keys(id text primary key,user_id text not null references users(id) on delete cascade,name text not null,prefix text not null,key_hash text unique not null,active boolean not null default true,spend_limit_toman numeric(18,2),total_spent_toman numeric(18,2) not null default 0,last_used_at timestamptz,created_at timestamptz not null default now());
create table if not exists providers(id text primary key,key text unique not null,name text not null,active boolean not null default true,balance_usd numeric(18,6),notes text,created_at timestamptz not null default now());
create table if not exists models(id text primary key,slug text unique not null,display_name text not null,provider_id text not null references providers(id),provider_model text not null,modality text not null default 'text',active boolean not null default false,input_cost_m_usd numeric(18,6) not null default 0,output_cost_m_usd numeric(18,6) not null default 0,markup_percent numeric(8,2) not null default 10,tags text not null default '',created_at timestamptz not null default now());
create table if not exists usage_records(id text primary key,user_id text not null references users(id),api_key_id text references api_keys(id),provider_id text not null references providers(id),model_id text not null references models(id),input_tokens int not null default 0,output_tokens int not null default 0,cost_usd numeric(18,8) not null default 0,charged_toman numeric(18,2) not null default 0,latency_ms int not null default 0,status text not null default 'success',request_id text,created_at timestamptz not null default now());
create table if not exists wallet_transactions(id text primary key,user_id text not null references users(id),type text not null,amount_toman numeric(18,2) not null,note text,created_at timestamptz not null default now());
create table if not exists provider_expenses(id text primary key,provider_id text not null references providers(id),amount_usd numeric(18,6) not null default 0,amount_toman numeric(18,2) not null default 0,note text,created_at timestamptz not null default now());
create table if not exists ai_conversations(id text primary key,user_id text not null references users(id) on delete cascade,workspace text not null default 'simple',title text not null default 'گفت‌وگوی جدید',model_slug text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists ai_messages(id text primary key,conversation_id text not null references ai_conversations(id) on delete cascade,role text not null,content text not null,input_tokens int not null default 0,output_tokens int not null default 0,charged_toman numeric(18,2) not null default 0,created_at timestamptz not null default now());
`);
 let {rows}=await pool.query("select id from providers where key='cloudflare'");let pid=rows[0]?.id;if(!pid){pid=crypto.randomUUID();await pool.query('insert into providers(id,key,name,notes) values($1,$2,$3,$4)',[pid,'cloudflare','Cloudflare AI Gateway','Unified Billing / Workers AI. Configure commercial rights before resale.'])}
 const seeds=[['gpt','GPT','openai/gpt-5.5','general,code'],['claude','Claude','anthropic/claude-sonnet-4-5','reasoning,writing,code'],['gemini','Gemini','google-ai-studio/gemini-2.5-flash','fast,business'],['deepseek','DeepSeek','deepseek/deepseek-chat','value,code'],['llama','Llama','@cf/meta/llama-3.3-70b-instruct-fp8-fast','open,fast']];
 for(const [slug,name,pm,tags] of seeds){await pool.query('insert into models(id,slug,display_name,provider_id,provider_model,tags,active) values($1,$2,$3,$4,$5,$6,false) on conflict(slug) do nothing',[crypto.randomUUID(),slug,name,pid,pm,tags])}
 await pool.query("update models set provider_model='google-ai-studio/gemini-2.5-flash',input_cost_m_usd=0.315,output_cost_m_usd=2.625,markup_percent=15,tags='fast,business,simple_default',active=true where slug='gemini' and input_cost_m_usd=0 and output_cost_m_usd=0");
}

app.get('/',(req,res)=>{const boot=JSON.stringify({authenticated:!!req.user,freeCredit:FREE_CREDIT});res.send(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bavaan AI · هوش مصنوعی، دقیقاً برای کاری که می‌خواهی</title><meta name="description" content="دسترسی PAYG به مدل‌های هوش مصنوعی با یک API، کیف پول ریالی و Workspace متناسب با نوع استفاده."><link rel="stylesheet" href="/static/landing/app.css?v=${esc(ASSET_VERSION)}"></head><body><div id="saas-landing-root"></div><script>window.__BAVAAN__=${boot}</script><script defer src="/static/landing/app.js?v=${esc(ASSET_VERSION)}"></script></body></html>`)});
app.get('/models',async(req,res)=>{const {rows}=await pool.query('select m.*,p.name provider_name from models m join providers p on p.id=m.provider_id order by m.display_name');res.send(base('مدل‌ها',`${publicHeader(req.user)}<div class="wrap section"><span class="badge">Model Catalog</span><h1>مدل‌ها</h1><p class="sectionlead">کاتالوگ یکپارچه. مدل‌ها بعد از نهایی‌شدن قیمت و upstream توسط ادمین فعال می‌شوند.</p><div class="card">${rows.map(m=>`<div class="modelrow"><b>${esc(m.display_name)}</b><span dir="ltr">${esc(m.slug)}</span><span>${esc(m.provider_name)}</span><span class="pill">${m.active?'فعال':'در حال آماده‌سازی'}</span></div>`).join('')}</div></div>`))});
app.get('/pricing',(req,res)=>res.send(base('قیمت‌گذاری',`${publicHeader(req.user)}<div class="wrap section"><span class="badge">قیمت‌گذاری ساده</span><h1>اشتراک نداریم. فقط مصرف.</h1><p class="sectionlead">کیف پول را شارژ می‌کنی و به اندازه‌ی مصرف پرداخت می‌کنی. قیمت هر مدل قبل از استفاده مشخص است.</p><div class="grid3"><div class="card"><h3>شروع</h3><h2>رایگان</h2><p>${toman(FREE_CREDIT)} اعتبار تست.</p></div><div class="card"><h3>PAYG</h3><h2>بدون پلن</h2><p>هزینه‌ی مدل + کارمزد شفاف، بدون تعهد ماهانه.</p></div><div class="card"><h3>مصرف بالا</h3><h2>Volume</h2><p>تخفیف بر اساس حجم مصرف، همچنان PAYG.</p></div></div></div>`)));
app.get('/docs',(req,res)=>res.send(base('مستندات',`${publicHeader(req.user)}<div class="doclayout"><aside class="docsnav"><b>مستندات</b><a href="#start">شروع سریع</a><a href="#auth">API Key</a><a href="#billing">Billing</a></aside><article class="docs"><span class="badge">Docs</span><h1>یک API شبیه OpenAI</h1><p class="sectionlead">برای مهاجرت معمولاً فقط Base URL و API Key را عوض می‌کنی.</p><h2 id="start">شروع سریع</h2><pre class="code">curl ${APP_URL}/api/v1/chat/completions \\
-H "Authorization: Bearer bv_YOUR_KEY" \\
-H "Content-Type: application/json" \\
-d '{"model":"gemini","messages":[{"role":"user","content":"سلام"}]}'</pre><h2 id="auth">API Key</h2><p>از Dashboard ← API Keys یک کلید بساز. مقدار کامل فقط یک بار نمایش داده می‌شود.</p><h2 id="billing">شفافیت هزینه</h2><p>Input، Output، هزینه upstream، مبلغ کسرشده، latency و request ID برای هر درخواست ثبت می‌شود.</p></article></div>`)));


function assistantText(data){
 const content=data?.choices?.[0]?.message?.content;
 if(typeof content==='string')return content;
 if(Array.isArray(content))return content.map(x=>typeof x==='string'?x:(x?.text||'')).join('\n').trim();
 return data?.output_text||data?.response?.output_text||'';
}
async function runPaidChat({userId,modelSlug='auto',messages,apiKeyId=null}){
 const account=process.env.CLOUDFLARE_ACCOUNT_ID,token=process.env.CLOUDFLARE_API_TOKEN;
 if(!account||!token){const e=new Error('اتصال Provider هنوز تنظیم نشده است.');e.status=503;throw e}
 let mq;
 if(modelSlug&&modelSlug!=='auto'){
  mq=await pool.query("select m.*,p.key provider_key,p.id provider_id from models m join providers p on p.id=m.provider_id where m.slug=$1 and m.active=true and m.modality='text'",[modelSlug]);
 }else{
  mq=await pool.query("select m.*,p.key provider_key,p.id provider_id from models m join providers p on p.id=m.provider_id where m.active=true and m.modality='text' order by case when m.tags like '%simple_default%' then 0 else 1 end,(m.input_cost_m_usd+m.output_cost_m_usd) asc limit 1");
 }
 const model=mq.rows[0];
 if(!model){const e=new Error('فعلاً مدل متنی فعالی برای این درخواست وجود ندارد.');e.status=503;throw e}
 if(model.provider_key!=='cloudflare'){const e=new Error('Adapter این Provider هنوز فعال نشده است.');e.status=501;throw e}
 const started=Date.now();
 const upstream=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/ai/v1/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','cf-aig-gateway-id':CLOUDFLARE_GATEWAY_ID},body:JSON.stringify({model:model.provider_model,messages,stream:false})});
 const data=await upstream.json().catch(()=>({}));
 if(!upstream.ok){const e=new Error(data?.errors?.[0]?.message||data?.error?.message||'Provider پاسخ نداد.');e.status=upstream.status;e.details=data;throw e}
 const text=assistantText(data);
 let input=Number(data?.usage?.prompt_tokens||data?.usage?.input_tokens||0);
 let output=Number(data?.usage?.completion_tokens||data?.usage?.output_tokens||0);
 if(!input)input=Math.max(1,Math.ceil(JSON.stringify(messages).length/4));
 if(!output)output=Math.max(1,Math.ceil(String(text).length/4));
 const costUsd=input/1e6*Number(model.input_cost_m_usd)+output/1e6*Number(model.output_cost_m_usd);
 const charge=Math.max(1,Math.ceil(costUsd*USD_TO_TOMAN*(1+Number(model.markup_percent)/100)));
 const usageId=crypto.randomUUID();
 await pool.query('begin');
 try{
  const bal=await pool.query('select wallet_balance_toman,status from users where id=$1 for update',[userId]);
  if(!bal.rowCount||bal.rows[0].status!=='active'){const e=new Error('حساب کاربری فعال نیست.');e.status=403;throw e}
  if(Number(bal.rows[0].wallet_balance_toman)<charge){const e=new Error('موجودی کیف پول کافی نیست.');e.status=402;throw e}
  await pool.query('update users set wallet_balance_toman=wallet_balance_toman-$1 where id=$2',[charge,userId]);
  if(apiKeyId)await pool.query('update api_keys set total_spent_toman=total_spent_toman+$1,last_used_at=now() where id=$2',[charge,apiKeyId]);
  await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'usage',$3,$4)",[crypto.randomUUID(),userId,-charge,`${model.display_name} AI usage`]);
  await pool.query("insert into usage_records(id,user_id,api_key_id,provider_id,model_id,input_tokens,output_tokens,cost_usd,charged_toman,latency_ms,status,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'success',$11)",[usageId,userId,apiKeyId,model.provider_id,model.id,input,output,costUsd,charge,Date.now()-started,data?.id||null]);
  await pool.query('commit');
 }catch(e){await pool.query('rollback');throw e}
 return {data,text,model,input,output,costUsd,charge,latencyMs:Date.now()-started,requestId:data?.id||usageId};
}
function modeInstruction(mode){
 const map={
  write:'تو یک دستیار حرفه‌ای نویسندگی فارسی هستی. متن شفاف، طبیعی و متناسب با درخواست کاربر بنویس.',
  translate:'تو مترجم حرفه‌ای هستی. متن را دقیق و روان ترجمه کن و اگر زبان مقصد مشخص نیست از کاربر بخواه مشخص کند.',
  summarize:'تو یک دستیار تحلیل و خلاصه‌سازی هستی. نکات اصلی را دقیق و ساختاریافته استخراج کن.',
  creative:'تو دستیار ایده‌پردازی و پرامپت‌نویسی خلاق هستی. برای محتوا، تصویر و ویدئو ایده و پرامپت عملی بده.',
  chat:'تو دستیار عمومی Bavaan AI هستی. پاسخ مفید، دقیق و مستقیم بده.'
 };
 return map[mode]||map.chat;
}
app.get('/register',(req,res)=>{if(req.user)return res.redirect('/dashboard');res.send(base('ثبت‌نام',`<div class="authpage"><div class="authcard"><a href="/" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><h1>حسابت رو بساز</h1><p class="sub">بدون خرید اولیه، با ${toman(FREE_CREDIT)} اعتبار هدیه.</p>${flash(req)}<form class="stack" method="post" action="/register"><input type="hidden" name="_csrf" value="${csrf(req)}"><input name="name" placeholder="نام"><input name="email" type="email" dir="ltr" placeholder="Email" required><input name="password" type="password" dir="ltr" minlength="8" placeholder="رمز عبور، حداقل ۸ کاراکتر" required><button class="btn primary">ساخت حساب</button></form>${process.env.GOOGLE_CLIENT_ID?`<div class="or">یا</div><a class="btn ghost wide" href="/auth/google">ثبت‌نام با Google</a>`:''}<p class="sub">حساب داری؟ <a href="/login">ورود</a></p></div></div>`))});
app.post('/register',checkCsrf,async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),pass=String(req.body.password||'');if(!email||pass.length<8){req.session.flash={type:'error',text:'ایمیل معتبر و رمز حداقل ۸ کاراکتری لازم است.'};return res.redirect('/register')}const ex=await pool.query('select 1 from users where email=$1',[email]);if(ex.rowCount){req.session.flash={type:'error',text:'این ایمیل قبلاً ثبت شده.'};return res.redirect('/register')}const id=crypto.randomUUID(),hash=await bcrypt.hash(pass,12),role=email===ADMIN_EMAIL?'admin':'user';await pool.query('insert into users(id,email,name,password_hash,role,wallet_balance_toman,free_credit_granted) values($1,$2,$3,$4,$5,$6,true)',[id,email,req.body.name||null,hash,role,FREE_CREDIT]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'free_credit',$3,$4)",[crypto.randomUUID(),id,FREE_CREDIT,'اعتبار هدیه شروع']);const {rows}=await pool.query('select * from users where id=$1',[id]);req.login(rows[0],e=>e?res.status(500).send('Login failed'):res.redirect('/onboarding'))});
app.get('/login',(req,res)=>{if(req.user)return res.redirect('/dashboard');res.send(base('ورود',`<div class="authpage"><div class="authcard"><a href="/" class="brand"><span class="brandmark">B</span><b>Bavaan AI</b></a><h1>خوش برگشتی</h1>${flash(req)}<form class="stack" method="post" action="/login"><input type="hidden" name="_csrf" value="${csrf(req)}"><input name="email" type="email" dir="ltr" placeholder="Email" required><input name="password" type="password" dir="ltr" placeholder="رمز عبور" required><button class="btn primary">ورود</button></form>${process.env.GOOGLE_CLIENT_ID?`<div class="or">یا</div><a class="btn ghost wide" href="/auth/google">ورود با Google</a>`:''}<p class="sub">حساب نداری؟ <a href="/register">ثبت‌نام</a></p></div></div>`))});
app.post('/login',checkCsrf,async(req,res)=>{const {rows}=await pool.query('select * from users where email=$1',[String(req.body.email||'').toLowerCase()]);const u=rows[0];if(!u?.password_hash||!(await bcrypt.compare(String(req.body.password||''),u.password_hash))){req.session.flash={type:'error',text:'ایمیل یا رمز عبور درست نیست.'};return res.redirect('/login')}req.login(u,e=>e?res.status(500).send('Login failed'):res.redirect(u.onboarding_done?'/dashboard':'/onboarding'))});
app.get('/auth/google',(req,res,next)=>process.env.GOOGLE_CLIENT_ID?passport.authenticate('google',{scope:['profile','email']})(req,res,next):res.redirect('/login'));
app.get('/auth/google/callback',(req,res,next)=>passport.authenticate('google',{failureRedirect:'/login'})(req,res,()=>res.redirect(req.user.onboarding_done?'/dashboard':'/onboarding')));
app.get('/logout',(req,res)=>req.logout(()=>res.redirect('/')));

app.get('/onboarding',guard,(req,res)=>res.send(base('شروع',`<div class="onboard"><span class="badge">کمتر از یک دقیقه</span><h1>بیشتر برای چه کاری می‌خوای از Bavaan استفاده کنی؟</h1><p class="sub">اسم دسته‌ها مهم نیست؛ چیزی رو انتخاب کن که شبیه خودته. بعداً هم می‌تونی عوضش کنی.</p><form method="post" action="/onboarding"><input type="hidden" name="_csrf" value="${csrf(req)}"><div class="choicegrid">${Object.entries(SEGMENTS).map(([k,s])=>`<label class="choice"><input type="radio" name="segment" value="${k}" required><b>${s.title}</b><span>${s.desc}</span></label>`).join('')}</div><button class="btn primary big">ورود به فضای من</button></form></div>`)));
app.post('/onboarding',guard,checkCsrf,async(req,res)=>{const s=SEGMENTS[req.body.segment];if(!s)return res.redirect('/onboarding');await pool.query('update users set segment=$1,workspace=$2,onboarding_done=true,updated_at=now() where id=$3',[req.body.segment,s.workspace,req.user.id]);req.user.segment=req.body.segment;req.user.workspace=s.workspace;req.user.onboarding_done=true;res.redirect('/dashboard')});
app.post('/workspace',guard,checkCsrf,async(req,res)=>{if(!WORKSPACES[req.body.workspace])return res.redirect('/dashboard');await pool.query('update users set workspace=$1,updated_at=now() where id=$2',[req.body.workspace,req.user.id]);req.user.workspace=req.body.workspace;res.redirect(req.get('referer')||'/dashboard')});

app.get('/dashboard',guard,async(req,res)=>{
 if(!req.user.onboarding_done)return res.redirect('/onboarding');
 const q=await pool.query('select coalesce(sum(charged_toman),0) spend,count(*) requests,coalesce(avg(latency_ms),0) latency from usage_records where user_id=$1',[req.user.id]);
 const k=await pool.query('select count(*) c from api_keys where user_id=$1 and active=true',[req.user.id]);
 const ws=req.user.workspace||'simple';const x=q.rows[0];
 let hero='';
 if(ws==='api'){
  hero=`<div class="workspacehero"><div class="card hero-card"><span class="badge">Developer Workspace</span><h2>از Playground تا Production</h2><p>مدل را تست کن، هزینه و latency را ببین، بعد همان درخواست را با API Key وارد محصولت کن.</p><div class="quickgrid"><a class="quick" href="/dashboard/ai"><b>Playground واقعی</b><small>ارسال درخواست و دیدن Token / Cost / Latency</small></a><a class="quick" href="/dashboard/api-keys"><b>کلیدهای API</b><small>کلید جدا برای تست و Production</small></a><a class="quick" href="/dashboard/models"><b>مدل‌های فعال</b><small>شناسه API و Provider</small></a></div></div><div class="card"><h3>شروع سریع</h3><p class="sub">اول یک مدل را در Playground تست کن.</p><a class="btn primary wide" href="/dashboard/ai">باز کردن Playground</a></div></div>`;
 }else if(ws==='simple'){
  hero=`<div class="simple-home"><div class="simple-welcome"><span class="badge">فضای ساده</span><h2>امروز می‌خوای چه کاری انجام بدی؟</h2><p>لازم نیست مدل انتخاب کنی. Bavaan پشت صحنه یک مدل مناسب و فعال را استفاده می‌کند.</p></div><div class="taskgrid"><a href="/dashboard/ai" class="taskcard"><b>گفت‌وگو و سؤال</b><span>هر چیزی بپرس و ادامه بده.</span></a><a href="/dashboard/ai?mode=write" class="taskcard"><b>نوشتن و بازنویسی</b><span>ایمیل، کپشن، متن و ایده.</span></a><a href="/dashboard/ai?mode=translate" class="taskcard"><b>ترجمه</b><span>ترجمه روان با حفظ معنی.</span></a><a href="/dashboard/ai?mode=summarize" class="taskcard"><b>خلاصه‌سازی</b><span>متن طولانی را کوتاه و قابل استفاده کن.</span></a></div></div>`;
 }else{
  hero=`<div class="workspacehero"><div class="card hero-card"><span class="badge">فضای پیشنهادی تو</span><h2>${WORKSPACES[ws]}</h2><p>ابزارها بر اساس نوع استفاده‌ات مرتب شده‌اند و Wallet و Usage بین همه Workspaceها مشترک است.</p><div class="quickgrid">${workspaceCards(ws)}</div></div><div class="card"><h3>AI Studio</h3><p>برای کار متنی همین حالا از محیط AI استفاده کن.</p><a class="btn primary wide" href="/dashboard/ai">باز کردن AI Studio</a></div></div>`;
 }
 res.send(appShell(req,'داشبورد',`<div class="dash"><div class="dashhead"><div><h1>سلام ${esc(req.user.name||'')}</h1><div class="sub">${WORKSPACES[ws]}</div></div></div><div class="stats"><div class="stat"><span>موجودی کیف پول</span><b>${toman(req.user.wallet_balance_toman)}</b></div><div class="stat"><span>مصرف کل</span><b>${toman(x.spend)}</b></div><div class="stat"><span>Request</span><b>${Number(x.requests).toLocaleString('fa-IR')}</b></div><div class="stat"><span>میانگین Latency</span><b>${Math.round(Number(x.latency||0)).toLocaleString('fa-IR')} ms</b></div></div>${hero}</div>`))
});

app.get('/dashboard/ai',guard,async(req,res)=>{
 if(!req.user.onboarding_done)return res.redirect('/onboarding');
 const ws=req.user.workspace||'simple';
 const allowedModes=['chat','write','translate','summarize','creative'];
 const mode=allowedModes.includes(String(req.query.mode||''))?String(req.query.mode):'chat';
 const [models,recent]=await Promise.all([
  pool.query("select slug,display_name,tags,input_cost_m_usd,output_cost_m_usd from models where active=true and modality='text' order by case when tags like '%simple_default%' then 0 else 1 end,display_name"),
  pool.query('select id,title,updated_at from ai_conversations where user_id=$1 order by updated_at desc limit 10',[req.user.id])
 ]);
 let conversation=null,messages=[];
 if(req.query.c){
  const cq=await pool.query('select * from ai_conversations where id=$1 and user_id=$2',[String(req.query.c),req.user.id]);
  conversation=cq.rows[0]||null;
  if(conversation){const mq=await pool.query('select role,content,charged_toman,created_at from ai_messages where conversation_id=$1 order by created_at asc limit 100',[conversation.id]);messages=mq.rows}
 }
 const developer=ws==='api'||ws==='production'||ws==='automation';
 const modelOptions=models.rows.map(m=>`<option value="${esc(m.slug)}" ${conversation?.model_slug===m.slug?'selected':''}>${esc(m.display_name)} · ${esc(m.slug)}</option>`).join('');
 const defaultModel=conversation?.model_slug||models.rows[0]?.slug||'';
 const recentHtml=recent.rows.map(x=>`<a href="/dashboard/ai?c=${encodeURIComponent(x.id)}" class="conversation-link ${conversation?.id===x.id?'active':''}"><b>${esc(x.title)}</b><small>${new Date(x.updated_at).toLocaleDateString('fa-IR')}</small></a>`).join('');
 const msgHtml=messages.map(m=>`<div class="chatmsg ${m.role==='user'?'user':'assistant'}"><div class="chatbubble">${esc(m.content).replace(/\n/g,'<br>')}</div>${m.role==='assistant'&&Number(m.charged_toman)>0?`<small>${toman(m.charged_toman)}</small>`:''}</div>`).join('');
 const modeTabs=[['chat','گفت‌وگو'],['write','نوشتن'],['translate','ترجمه'],['summarize','خلاصه‌سازی'],['creative','ایده‌پردازی']].map(([k,l])=>`<a class="modechip ${mode===k?'active':''}" href="/dashboard/ai?mode=${k}">${l}</a>`).join('');
 res.send(appShell(req,developer?'Playground':'Bavaan AI',`<div class="dash ai-page"><div class="ai-layout"><aside class="conversation-panel"><a class="btn primary wide" href="/dashboard/ai?mode=${mode}">گفت‌وگوی جدید</a><div class="conversation-list">${recentHtml||'<p class="sub">هنوز گفت‌وگویی نداری.</p>'}</div></aside><section class="ai-studio"><div class="ai-studio-head"><div><span class="badge">${developer?'Developer Playground':'Bavaan AI'}</span><h1>${developer?'مدل را تست کن و هزینه را همان لحظه ببین':'چه کاری می‌خوای انجام بدی؟'}</h1><p class="sub">${developer?'پاسخ، Token، Cost، Latency و Request ID در همین صفحه ثبت می‌شود.':'مدل مناسب پشت صحنه انتخاب می‌شود و هزینه از اعتبارت کم می‌شود.'}</p></div><div class="wallet-chip">موجودی: <b>${toman(req.user.wallet_balance_toman)}</b></div></div><div class="modechips">${modeTabs}</div>${developer?`<label class="model-control">مدل<select id="aiModel">${modelOptions}</select></label><details class="dev-snippet"><summary>نمونه کد همین مدل</summary><pre id="apiSnippet" data-base="${APP_URL}" data-model="${esc(defaultModel)}">curl ${APP_URL}/api/v1/chat/completions \\\n-H "Authorization: Bearer bv_YOUR_KEY" \\\n-H "Content-Type: application/json" \\\n-d '{"model":"${esc(defaultModel)}","messages":[{"role":"user","content":"سلام"}]}'</pre></details>`:''}<div id="chatMessages" class="chat-messages">${msgHtml||'<div class="chat-empty"><b>آماده‌ام.</b><span>درخواستت را پایین بنویس.</span></div>'}</div><form id="aiComposer" class="ai-composer" data-csrf="${csrf(req)}" data-conversation="${conversation?.id||''}" data-mode="${mode}" data-developer="${developer?'1':'0'}"><textarea id="aiPrompt" rows="3" maxlength="12000" placeholder="${mode==='write'?'مثلاً: یک متن معرفی کوتاه برای محصولم بنویس…':mode==='translate'?'متنی که می‌خوای ترجمه بشه را اینجا بنویس…':mode==='summarize'?'متن طولانی را اینجا قرار بده…':'پیامت را بنویس…'}" required></textarea><div class="composer-actions"><div id="aiMeta" class="ai-meta">هزینه بعد از پاسخ نمایش داده می‌شود.</div><button id="aiSend" class="btn primary" type="submit">ارسال</button></div></form></section></div></div><script defer src="/static/workspace-ai.js?v=${esc(ASSET_VERSION)}"></script>`))
});

app.post('/dashboard/ai/chat',guard,checkCsrf,async(req,res)=>{
 try{
  const prompt=String(req.body.prompt||'').trim();if(!prompt)return res.status(400).json({ok:false,error:'پیام خالی است.'});if(prompt.length>12000)return res.status(400).json({ok:false,error:'متن درخواست بیش از حد طولانی است.'});
  const ws=req.user.workspace||'simple';const mode=['chat','write','translate','summarize','creative'].includes(req.body.mode)?req.body.mode:'chat';
  let conv=null;
  if(req.body.conversation_id){const cq=await pool.query('select * from ai_conversations where id=$1 and user_id=$2',[String(req.body.conversation_id),req.user.id]);conv=cq.rows[0]||null}
  if(!conv){conv={id:crypto.randomUUID(),user_id:req.user.id,workspace:ws,title:prompt.replace(/\s+/g,' ').slice(0,58)+(prompt.length>58?'…':''),model_slug:null};await pool.query('insert into ai_conversations(id,user_id,workspace,title) values($1,$2,$3,$4)',[conv.id,req.user.id,ws,conv.title])}
  const history=await pool.query("select role,content from ai_messages where conversation_id=$1 and role in ('user','assistant') order by created_at desc limit 18",[conv.id]);
  const chronological=history.rows.reverse();
  const developer=ws==='api'||ws==='production'||ws==='automation';
  const requestedModel=developer&&req.body.model?String(req.body.model):'auto';
  const chatMessages=[{role:'system',content:modeInstruction(mode)},...chronological,{role:'user',content:prompt}];
  const result=await runPaidChat({userId:req.user.id,modelSlug:requestedModel,messages:chatMessages});
  await pool.query('begin');
  try{
   await pool.query("insert into ai_messages(id,conversation_id,role,content) values($1,$2,'user',$3)",[crypto.randomUUID(),conv.id,prompt]);
   await pool.query("insert into ai_messages(id,conversation_id,role,content,input_tokens,output_tokens,charged_toman) values($1,$2,'assistant',$3,$4,$5,$6)",[crypto.randomUUID(),conv.id,result.text,result.input,result.output,result.charge]);
   await pool.query('update ai_conversations set model_slug=$1,updated_at=now() where id=$2',[result.model.slug,conv.id]);
   await pool.query('commit');
  }catch(e){await pool.query('rollback');throw e}
  const b=await pool.query('select wallet_balance_toman from users where id=$1',[req.user.id]);req.user.wallet_balance_toman=b.rows[0].wallet_balance_toman;
  res.json({ok:true,conversation_id:conv.id,answer:result.text,model:result.model.slug,input_tokens:result.input,output_tokens:result.output,charged_toman:result.charge,latency_ms:result.latencyMs,request_id:result.requestId,wallet_balance_toman:Number(b.rows[0].wallet_balance_toman)});
 }catch(e){console.error(e);res.status(e.status||500).json({ok:false,error:e.message||'خطایی در اجرای مدل رخ داد.'})}
});

app.get('/dashboard/models',guard,async(req,res)=>{const {rows}=await pool.query('select m.*,p.name provider_name from models m join providers p on p.id=m.provider_id order by m.display_name');res.send(appShell(req,'مدل‌ها',`<div class="dash"><h1>مدل‌ها</h1><p class="sub">شناسه پایدار Bavaan و upstream پشت آن.</p><div class="card"><table class="table"><tr><th>مدل</th><th>شناسه API</th><th>Provider</th><th>وضعیت</th></tr>${rows.map(m=>`<tr><td><b>${esc(m.display_name)}</b></td><td dir="ltr">${esc(m.slug)}</td><td>${esc(m.provider_name)}</td><td><span class="pill">${m.active?'فعال':'غیرفعال'}</span></td></tr>`).join('')}</table></div></div>`))});
app.get('/dashboard/api-keys',guard,async(req,res)=>{const {rows}=await pool.query('select * from api_keys where user_id=$1 order by created_at desc',[req.user.id]);const raw=req.session.newKey;delete req.session.newKey;res.send(appShell(req,'API Keys',`<div class="dash"><div class="dashhead"><div><h1>API Keys</h1><p class="sub">برای پروژه‌ها یا مشتری‌ها کلید جدا بساز.</p></div><form method="post" action="/dashboard/api-keys"><input type="hidden" name="_csrf" value="${csrf(req)}"><button class="btn primary">ساخت API Key</button></form></div>${raw?`<div class="secretbox"><b>این کلید فقط همین یک‌بار نمایش داده می‌شود:</b><code>${esc(raw)}</code></div>`:''}<div class="card"><table class="table"><tr><th>نام</th><th>کلید</th><th>مصرف</th><th>آخرین استفاده</th></tr>${rows.map(k=>`<tr><td>${esc(k.name)}</td><td dir="ltr">${esc(k.prefix)}••••••</td><td>${toman(k.total_spent_toman)}</td><td>${k.last_used_at?new Date(k.last_used_at).toLocaleString('fa-IR'):'—'}</td></tr>`).join('')}</table></div></div>`))});
app.post('/dashboard/api-keys',guard,checkCsrf,async(req,res)=>{const raw='bv_'+crypto.randomBytes(24).toString('hex'),hash=crypto.createHash('sha256').update(raw).digest('hex');await pool.query('insert into api_keys(id,user_id,name,prefix,key_hash) values($1,$2,$3,$4,$5)',[crypto.randomUUID(),req.user.id,'کلید '+new Date().toLocaleDateString('fa-IR'),raw.slice(0,11),hash]);req.session.newKey=raw;res.redirect('/dashboard/api-keys')});
app.get('/dashboard/usage',guard,async(req,res)=>{const {rows}=await pool.query('select u.*,m.display_name from usage_records u join models m on m.id=u.model_id where u.user_id=$1 order by u.created_at desc limit 100',[req.user.id]);res.send(appShell(req,'مصرف و هزینه',`<div class="dash"><h1>مصرف و هزینه</h1><p class="sub">شفافیت request-level.</p><div class="card"><table class="table"><tr><th>زمان</th><th>مدل</th><th>Input / Output</th><th>Latency</th><th>هزینه</th></tr>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('fa-IR')}</td><td>${esc(x.display_name)}</td><td>${x.input_tokens.toLocaleString('fa-IR')} / ${x.output_tokens.toLocaleString('fa-IR')}</td><td>${x.latency_ms}ms</td><td>${toman(x.charged_toman)}</td></tr>`).join('')}</table></div></div>`))});
app.get('/dashboard/billing',guard,async(req,res)=>{const {rows}=await pool.query('select * from wallet_transactions where user_id=$1 order by created_at desc limit 100',[req.user.id]);res.send(appShell(req,'کیف پول',`<div class="dash"><h1>کیف پول</h1><div class="stats"><div class="stat"><span>موجودی</span><b>${toman(req.user.wallet_balance_toman)}</b></div><div class="stat"><span>مدل پرداخت</span><b>PAYG</b></div></div><div class="card mt"><h3>گردش کیف پول</h3><table class="table">${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('fa-IR')}</td><td>${esc(x.note||x.type)}</td><td dir="ltr" class="${Number(x.amount_toman)>=0?'metricgood':'metricbad'}">${toman(x.amount_toman)}</td></tr>`).join('')}</table></div></div>`))});
app.get('/dashboard/settings',guard,(req,res)=>res.send(appShell(req,'تنظیمات',`<div class="dash"><h1>تنظیمات</h1><div class="card"><h3>نوع استفاده‌ی اصلی</h3><p class="sub">این انتخاب فقط پیشنهادهای Workspace را تنظیم می‌کند؛ هر زمان قابل تغییر است.</p><form method="post" action="/dashboard/settings" class="stack narrow"><input type="hidden" name="_csrf" value="${csrf(req)}"><select name="segment">${Object.entries(SEGMENTS).map(([k,s])=>`<option value="${k}" ${req.user.segment===k?'selected':''}>${s.title}</option>`).join('')}</select><button class="btn primary">ذخیره و تغییر Workspace پیشنهادی</button></form></div></div>`)));
app.post('/dashboard/settings',guard,checkCsrf,async(req,res)=>{const s=SEGMENTS[req.body.segment];if(s){await pool.query('update users set segment=$1,workspace=$2,updated_at=now() where id=$3',[req.body.segment,s.workspace,req.user.id]);req.user.segment=req.body.segment;req.user.workspace=s.workspace}res.redirect('/dashboard/settings')});

app.get('/admin',adminGuard,async(req,res)=>{const [users,usage,exp,wallet,segments,topModels]=await Promise.all([pool.query('select count(*) c from users'),pool.query('select count(*) requests,coalesce(sum(charged_toman),0) revenue,coalesce(sum(cost_usd),0) cost_usd from usage_records'),pool.query('select coalesce(sum(amount_toman),0) c from provider_expenses'),pool.query('select coalesce(sum(wallet_balance_toman),0) c from users'),pool.query("select coalesce(segment,'unset') segment,count(*) c from users group by segment order by c desc"),pool.query('select m.display_name,count(*) requests,coalesce(sum(u.charged_toman),0) revenue,coalesce(sum(u.cost_usd),0) cost_usd from usage_records u join models m on m.id=u.model_id group by m.display_name order by revenue desc limit 8')]);const revenue=Number(usage.rows[0].revenue),expense=Number(exp.rows[0].c),margin=revenue-expense;let insights=[];if(revenue>0&&margin/revenue<.12)insights.push('حاشیه سود ثبت‌شده زیر ۱۲٪ است؛ markup یا route مدل‌های پرترافیک را بررسی کن.');if(Number(wallet.rows[0].c)>revenue*2&&revenue>0)insights.push('تعهد کیف پول کاربران نسبت به درآمد ثبت‌شده بالاست؛ provider liquidity را کنترل کن.');if(!insights.length)insights.push('هنوز هشدار مالی جدی از داده‌های ثبت‌شده دیده نمی‌شود.');res.send(appShell(req,'ادمین',`<div class="dash"><h1>مرکز فرمان Bavaan</h1><p class="sub">رشد، مصرف، مالی و سلامت پلتفرم.</p><div class="stats"><div class="stat"><span>کاربر</span><b>${Number(users.rows[0].c).toLocaleString('fa-IR')}</b></div><div class="stat"><span>درآمد Usage</span><b>${toman(revenue)}</b></div><div class="stat"><span>هزینه Provider ثبت‌شده</span><b>${toman(expense)}</b></div><div class="stat"><span>Gross Result</span><b class="${margin>=0?'metricgood':'metricbad'}">${toman(margin)}</b></div></div><div class="admin-grid"><div class="card"><h3>Insightهای عملیاتی</h3>${insights.map(x=>`<p>• ${esc(x)}</p>`).join('')}<p>• تعهد کیف پول کاربران: <b>${toman(wallet.rows[0].c)}</b></p></div><div class="card"><h3>توزیع نوع استفاده</h3>${segments.rows.map(x=>`<div class="barline"><span>${esc(x.segment)}</span><b>${Number(x.c).toLocaleString('fa-IR')}</b></div>`).join('')}</div></div><div class="card mt"><h3>مدل‌های درآمدساز</h3><table class="table"><tr><th>مدل</th><th>Request</th><th>Revenue</th><th>Upstream Cost</th></tr>${topModels.rows.map(x=>`<tr><td>${esc(x.display_name)}</td><td>${x.requests}</td><td>${toman(x.revenue)}</td><td>${moneyUsd(x.cost_usd)}</td></tr>`).join('')}</table></div></div>`))});
app.get('/admin/users',adminGuard,async(req,res)=>{const {rows}=await pool.query("select u.*,count(distinct r.id) requests,count(distinct k.id) keys from users u left join usage_records r on r.user_id=u.id left join api_keys k on k.user_id=u.id group by u.id order by u.created_at desc limit 300");res.send(appShell(req,'کاربران',`<div class="dash"><h1>کاربران و کیف پول</h1><div class="card"><table class="table"><tr><th>کاربر</th><th>نوع</th><th>موجودی</th><th>Request / Keys</th><th>اصلاح کیف پول</th></tr>${rows.map(u=>`<tr><td><b>${esc(u.name||'—')}</b><br><small>${esc(u.email)}</small></td><td>${esc(u.segment||'—')}</td><td>${toman(u.wallet_balance_toman)}</td><td>${u.requests} / ${u.keys}</td><td><form class="inline" method="post" action="/admin/users/${u.id}/wallet"><input type="hidden" name="_csrf" value="${csrf(req)}"><input name="amount" class="mini" placeholder="± تومان"><button class="btn ghost">اعمال</button></form></td></tr>`).join('')}</table></div></div>`))});
app.post('/admin/users/:id/wallet',adminGuard,checkCsrf,async(req,res)=>{const amount=Number(req.body.amount);if(Number.isFinite(amount)&&amount!==0){await pool.query('begin');try{await pool.query('update users set wallet_balance_toman=wallet_balance_toman+$1 where id=$2',[amount,req.params.id]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'admin_adjustment',$3,$4)",[crypto.randomUUID(),req.params.id,amount,'اصلاح موجودی توسط ادمین']);await pool.query('commit')}catch(e){await pool.query('rollback');throw e}}res.redirect('/admin/users')});
app.get('/admin/finance',adminGuard,async(req,res)=>{const [providers,expenses,usage,wallet]=await Promise.all([pool.query('select * from providers order by name'),pool.query('select e.*,p.name provider_name from provider_expenses e join providers p on p.id=e.provider_id order by e.created_at desc limit 100'),pool.query('select coalesce(sum(charged_toman),0) revenue,coalesce(sum(cost_usd),0) cost from usage_records'),pool.query('select coalesce(sum(wallet_balance_toman),0) c from users')]);const expT=expenses.rows.reduce((s,x)=>s+Number(x.amount_toman),0);res.send(appShell(req,'مالی',`<div class="dash"><h1>مالی</h1><p class="sub">Provider spend، درآمد مصرف و تعهد کیف پول.</p><div class="financegrid"><div class="stat"><span>درآمد Usage</span><b>${toman(usage.rows[0].revenue)}</b></div><div class="stat"><span>Provider Expense</span><b>${toman(expT)}</b></div><div class="stat"><span>Wallet Liability</span><b>${toman(wallet.rows[0].c)}</b></div></div><div class="admin-grid mt"><div class="card"><h3>ثبت خرید / شارژ Provider</h3><form class="stack" method="post" action="/admin/finance"><input type="hidden" name="_csrf" value="${csrf(req)}"><select name="provider_id">${providers.rows.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><input name="amount_usd" placeholder="مبلغ دلار"><input name="amount_toman" placeholder="معادل تومان"><input name="note" placeholder="یادداشت"><button class="btn primary">ثبت هزینه</button></form></div><div class="card"><h3>آخرین هزینه‌ها</h3>${expenses.rows.slice(0,8).map(x=>`<div class="barline"><span>${esc(x.provider_name)}</span><b>${moneyUsd(x.amount_usd)} · ${toman(x.amount_toman)}</b></div>`).join('')}</div></div></div>`))});
app.post('/admin/finance',adminGuard,checkCsrf,async(req,res)=>{await pool.query('insert into provider_expenses(id,provider_id,amount_usd,amount_toman,note) values($1,$2,$3,$4,$5)',[crypto.randomUUID(),req.body.provider_id,Number(req.body.amount_usd||0),Number(req.body.amount_toman||0),req.body.note||null]);res.redirect('/admin/finance')});
app.get('/admin/models',adminGuard,async(req,res)=>{const [providers,models]=await Promise.all([pool.query('select * from providers order by name'),pool.query('select m.*,p.name provider_name from models m join providers p on p.id=m.provider_id order by m.display_name')]);res.send(appShell(req,'مدل‌ها و Providerها',`<div class="dash"><h1>مدل‌ها و Providerها</h1><div class="grid3">${providers.rows.map(p=>`<div class="card"><span class="pill">${p.active?'فعال':'غیرفعال'}</span><h3>${esc(p.name)}</h3><p>Balance: ${p.balance_usd?moneyUsd(p.balance_usd):'ثبت نشده'}</p></div>`).join('')}</div><div class="card mt"><table class="table"><tr><th>مدل</th><th>upstream</th><th>Input $/M</th><th>Output $/M</th><th>Markup</th><th>فعال</th></tr>${models.rows.map(m=>`<tr><td>${esc(m.display_name)}</td><td dir="ltr">${esc(m.provider_model)}</td><td colspan="4"><form class="inline" method="post" action="/admin/models/${m.id}"><input type="hidden" name="_csrf" value="${csrf(req)}"><input class="mini" name="input_cost" value="${m.input_cost_m_usd}"><input class="mini" name="output_cost" value="${m.output_cost_m_usd}"><input class="mini" name="markup" value="${m.markup_percent}"><label><input type="checkbox" name="active" ${m.active?'checked':''}> فعال</label><button class="btn ghost">ذخیره</button></form></td></tr>`).join('')}</table></div></div>`))});
app.post('/admin/models/:id',adminGuard,checkCsrf,async(req,res)=>{await pool.query('update models set input_cost_m_usd=$1,output_cost_m_usd=$2,markup_percent=$3,active=$4 where id=$5',[Number(req.body.input_cost||0),Number(req.body.output_cost||0),Number(req.body.markup||0),!!req.body.active,req.params.id]);res.redirect('/admin/models')});

app.post('/api/v1/chat/completions',async(req,res)=>{const started=Date.now();const raw=(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!raw.startsWith('bv_'))return res.status(401).json({error:{message:'Invalid API key'}});const hash=crypto.createHash('sha256').update(raw).digest('hex');const kq=await pool.query('select k.*,u.wallet_balance_toman,u.status from api_keys k join users u on u.id=k.user_id where k.key_hash=$1 and k.active=true',[hash]);const key=kq.rows[0];if(!key||key.status!=='active')return res.status(401).json({error:{message:'Invalid API key'}});if(req.body.stream)return res.status(400).json({error:{message:'stream=true is not enabled in the first provider adapter yet'}});const mq=await pool.query('select m.*,p.key provider_key,p.id provider_id from models m join providers p on p.id=m.provider_id where m.slug=$1 and m.active=true',[String(req.body.model||'')]);const model=mq.rows[0];if(!model)return res.status(404).json({error:{message:'Unknown or inactive model'}});if(Number(key.wallet_balance_toman)<=0)return res.status(402).json({error:{message:'Insufficient balance'}});if(model.provider_key!=='cloudflare')return res.status(501).json({error:{message:'Provider adapter not configured'}});const account=process.env.CLOUDFLARE_ACCOUNT_ID,token=process.env.CLOUDFLARE_API_TOKEN;if(!account||!token)return res.status(503).json({error:{message:'Provider credentials are not configured yet'}});
 const upstream=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/ai/v1/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','cf-aig-gateway-id':CLOUDFLARE_GATEWAY_ID},body:JSON.stringify({...req.body,model:model.provider_model,stream:false})});const data=await upstream.json();if(!upstream.ok)return res.status(upstream.status).json(data);const input=Number(data?.usage?.prompt_tokens||data?.usage?.input_tokens||0),output=Number(data?.usage?.completion_tokens||data?.usage?.output_tokens||0);const costUsd=input/1e6*Number(model.input_cost_m_usd)+output/1e6*Number(model.output_cost_m_usd);const charge=Math.max(1,Math.ceil(costUsd*USD_TO_TOMAN*(1+Number(model.markup_percent)/100)));const uid=crypto.randomUUID();await pool.query('begin');try{const bal=await pool.query('select wallet_balance_toman from users where id=$1 for update',[key.user_id]);if(Number(bal.rows[0].wallet_balance_toman)<charge){await pool.query('rollback');return res.status(402).json({error:{message:'Insufficient balance'}})}await pool.query('update users set wallet_balance_toman=wallet_balance_toman-$1 where id=$2',[charge,key.user_id]);await pool.query('update api_keys set total_spent_toman=total_spent_toman+$1,last_used_at=now() where id=$2',[charge,key.id]);await pool.query("insert into wallet_transactions(id,user_id,type,amount_toman,note) values($1,$2,'usage',$3,$4)",[crypto.randomUUID(),key.user_id,-charge,`${model.display_name} API usage`]);await pool.query("insert into usage_records(id,user_id,api_key_id,provider_id,model_id,input_tokens,output_tokens,cost_usd,charged_toman,latency_ms,status,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'success',$11)",[uid,key.user_id,key.id,model.provider_id,model.id,input,output,costUsd,charge,Date.now()-started,data?.id||null]);await pool.query('commit')}catch(e){await pool.query('rollback');throw e}res.json({...data,model:model.slug,bavaan:{charged_toman:charge}})});
app.get('/api/v1/models',async(req,res)=>{const {rows}=await pool.query('select slug,display_name,modality,tags from models where active=true order by display_name');res.json({object:'list',data:rows.map(m=>({id:m.slug,object:'model',name:m.display_name,modality:m.modality,tags:m.tags.split(',').filter(Boolean)}))})});
app.get('/healthz',(_req,res)=>res.json({ok:true}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).send(base('خطا','<div class="authpage"><div class="authcard"><h1>خطایی پیش آمد</h1><p class="sub">دوباره تلاش کن یا با پشتیبانی تماس بگیر.</p></div></div>'))});

initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Bavaan AI listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
